---
kind: pipeline
type: docker
name: default

steps:
  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token: ${TELEGRAM_TOKEN}
      to: ${TELEGRAM_CLIENT}
