---
kind: pipeline
name: on commit

steps:
  - name: Check that version file has been updated
    image: curlimages/curl
    commands:
      - echo ${GITHUB_API_KEY}
      # - sh auto_create_tag.sh
trigger:
  branch:
  - master

---
kind: pipeline
name: on tag

steps:
  - name: build docker imagee
    image: plugins/docker
    settings:
      repo: andrchalov/docker-ci-test
      username: andrchalov
      password:
        from_secret: DOCKER_REGISTRY_TOKEN
      tags:
        - ${DRONE_TAG}

  - name: publish release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_API_KEY
  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: TELEGRAM_TOKEN
      to:
        from_secret: TELEGRAM_CLIENT
    when:
      status: [ success, failure ]
      event: [ push, tag, deployment, pull_request ]
trigger:
  event:
  - tag
