---
kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      auth:
        from_secret: DOCKER_REGISTRY_TOKEN
  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: TELEGRAM_TOKEN
      to:
        from_secret: TELEGRAM_CLIENT
