---
kind: pipeline
name: default

steps:
  - name: docker-tag-demo
    image: debian:stable-slim
    commands:
      - echo "The current branch is ${DRONE_BRANCH}"
      - echo "The current commit hash is ${DRONE_COMMIT_SHA}"
      - echo "The image tag is ${DRONE_TAG}"
#   - name: docker
#     image: plugins/docker
#     settings:
#       repo: andrchalov/docker-ci-test
#       username: andrchalov
#       password:
#         from_secret: DOCKER_REGISTRY_TOKEN
#       tags:
#         - ${DRONE_TAG}
  - name: set version
    image: alpine
    commands:
      - echo "${DRONE_TAG}" > src/version
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_API_KEY
      files: src/*
    when:
      event: tag
  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: TELEGRAM_TOKEN
      to:
        from_secret: TELEGRAM_CLIENT
    when:
      status: [ success, failure ]
      event: [ push, tag, deployment, pull_request ]
trigger:
  event:
  - tag
